CREATE SCHEMA GD;
GO

CREATE TABLE GD.PAIS(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE GD.USUARIO(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    APELLIDO NVARCHAR(100) NOT NULL,
    CORREO NVARCHAR(100) NOT NULL UNIQUE,
    FOTO NVARCHAR(100),
    ID_PAIS INT,
    CONSTRAINT FK_USUARIO_PAIS FOREIGN KEY (ID_PAIS)
        REFERENCES GD.PAIS(ID)
);
GO

CREATE TABLE GD.MEMBRESIA(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL
);
GO

CREATE TABLE GD.UNIDAD(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    CAPACIDAD_TOTAL DECIMAL(10,2) NOT NULL,
    CAPACIDAD_ACTUAL DECIMAL(10,2) NOT NULL,
    FECHA_COMPRA DATE,
    FECHA_EXPIRACION DATE,
    ID_USUARIO INT,
    ID_MEMBRESIA INT,
    CONSTRAINT FK_UNIDAD_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_UNIDAD_MEMBRESIA FOREIGN KEY (ID_MEMBRESIA)
        REFERENCES GD.MEMBRESIA(ID)
);
GO

CREATE TABLE GD.CARPETA(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_CARPETA_PADRE INT NULL,  
    NOMBRE NVARCHAR(100) NOT NULL,  
    TAMAÑO DECIMAL(10,2) NOT NULL,
    VISIBILIDAD CHAR(1),
    FECHA_CREACION DATE NOT NULL,
    FECHA_MODIFICACION DATE NOT NULL,
    CONSTRAINT FK_CARPETA_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_CARPETA_PADRE FOREIGN KEY (ID_CARPETA_PADRE)
        REFERENCES GD.CARPETA(ID)
);
GO

CREATE TABLE GD.ICONOS(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100),
    URL NVARCHAR(150)
);
GO

CREATE TABLE GD.ARCHIVO(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_CARPETA INT,
    ID_ICONO INT NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    TIPO NVARCHAR(100) NOT NULL,
    TAMAÑO DECIMAL(10,2) NOT NULL,
    URL NVARCHAR(100) NOT NULL UNIQUE,
    VISIBILIDAD CHAR(1),
    FECHA_CREACION DATE NOT NULL,
    FECHA_MODIFICACION DATE NOT NULL,
    CONSTRAINT FK_ARCHIVO_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_ARCHIVO_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_ICONO_CARPETA FOREIGN KEY (ID_ICONO)
        REFERENCES GD.ICONOS(ID)
);
GO

CREATE TABLE GD.PAPELERA(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_CARPETA INT,
    ID_ARCHIVO INT,
    TAMAÑO DECIMAL(10,2) NOT NULL,
    FECHA_ENTRADA DATE NOT NULL,
    FECHA_ELIMINACION DATE NOT NULL,
    CONSTRAINT FK_PAPELERA_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_PAPELERA_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_PAPELERA_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.VERSION(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_ARCHIVO INT NOT NULL,
    NUMERO_VERSION VARCHAR(100),
    URL NVARCHAR(100) NOT NULL,
    FECHA DATE NOT NULL,
    CONSTRAINT FK_VERSION_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_VERSION_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.COMENTARIOS(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_ARCHIVO INT NOT NULL,
    TEXTO NVARCHAR(100) NOT NULL,
    FECHA DATE NOT NULL,
    CONSTRAINT FK_COMENTARIO_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_COMENTARIO_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.SPAM(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_ARCHIVO INT,
    ID_CARPETA INT,
    FECHA DATE NOT NULL,
    CONSTRAINT FK_SPAM_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_SPAM_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_SPAM_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.FAVORITOS(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_CARPETA INT NOT NULL,
    ID_ARCHIVO INT NOT NULL,
    FECHA_AGREGADO DATE NOT NULL,
    CONSTRAINT FK_FAVORITOS_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_FAVORITOS_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_FAVORITOS_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.DESCARGAS(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_ARCHIVO INT,
    ID_CARPETA INT,
    DESTINO_DESCARGA NVARCHAR(100) NOT NULL,
    FECHA_DESCARGA DATE NOT NULL,
    FECHA_ACTUALIZACION DATE NOT NULL,
    CONSTRAINT FK_DESCARGAS_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_DESCARGAS_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_DESCARGAS_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.PERMISOS(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    DESCRIPCION NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE GD.ARCHIVO_PERMISO(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_ARCHIVO INT NOT NULL,
    ID_PERMISO INT NOT NULL,
    CONSTRAINT FK_ARCHIVOPERMISO_PERMISO FOREIGN KEY (ID_PERMISO)
        REFERENCES GD.PERMISOS(ID),
    CONSTRAINT FK_ARCHIVOPERMISO_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.CARPETA_PERMISO(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_CARPETA INT NOT NULL,
    ID_PERMISO INT NOT NULL,
    CONSTRAINT FK_CARPETAPERMISO_PERMISO FOREIGN KEY (ID_PERMISO)
        REFERENCES GD.PERMISOS(ID),
    CONSTRAINT FK_CARPETAPERMISO_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID)
);
GO

CREATE TABLE GD.COMPARTIDOS(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_ARCHIVO INT,
    ID_CARPETA INT,
    ID_PERMISO INT NOT NULL,
    CONSTRAINT FK_COMPARTIDO_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_COMPARTIDO_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_COMPARTIDO_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID),
    CONSTRAINT FK_COMPARTIDO_PERMISO FOREIGN KEY (ID_PERMISO)
        REFERENCES GD.PERMISOS(ID)
);
GO