INSERT INTO PAIS (NOMBRE) VALUES ('Honduras');
INSERT INTO PAIS (NOMBRE) VALUES ('Guatemala');
INSERT INTO PAIS (NOMBRE) VALUES ('El Salvador');
INSERT INTO PAIS (NOMBRE) VALUES ('Costa Rica');

INSERT INTO USUARIO (NOMBRE, APELLIDO, CORREO, FOTO, ID_PAIS)
VALUES ('Kevin', 'Flores', 'kevin@mail.com', 'kevin.jpg', 1);

INSERT INTO USUARIO (NOMBRE, APELLIDO, CORREO, FOTO, ID_PAIS)
VALUES ('Ana', 'López', 'ana@mail.com', 'ana.png', 2);

INSERT INTO USUARIO (NOMBRE, APELLIDO, CORREO, FOTO, ID_PAIS)
VALUES ('Carlos', 'Martinez', 'carlos@mail.com', NULL, 1);

INSERT INTO MEMBRESIA (NOMBRE, PRECIO) VALUES ('Gratis', 0);
INSERT INTO MEMBRESIA (NOMBRE, PRECIO) VALUES ('Premium', 9.99);
INSERT INTO MEMBRESIA (NOMBRE, PRECIO) VALUES ('Enterprise', 19.99);

-- Usuario 1 (Gratis)
INSERT INTO UNIDAD (ID_USUARIO, ID_MEMBRESIA) VALUES (1, 1);

-- Usuario 2 (Premium)
INSERT INTO UNIDAD (ID_USUARIO, ID_MEMBRESIA) VALUES (2, 2);

-- Usuario 3 (Ultimate)
INSERT INTO UNIDAD (ID_USUARIO, ID_MEMBRESIA) VALUES (3, 3);

-- Carpetas de usuario 1
INSERT INTO CARPETA (ID_USUARIO, NOMBRE) VALUES (1, 'Documentos');
INSERT INTO CARPETA (ID_USUARIO, ID_CARPETA_PADRE, NOMBRE) VALUES (1, 1, 'Tareas');

-- Carpeta usuario 2
INSERT INTO CARPETA (ID_USUARIO, NOMBRE) VALUES (2, 'Fotos');

INSERT INTO ICONOS (NOMBRE, URL) VALUES ('PDF', 'pdf.png');
INSERT INTO ICONOS (NOMBRE, URL) VALUES ('Word', 'doc.png');
INSERT INTO ICONOS (NOMBRE, URL) VALUES ('Imagen', 'img.png');

INSERT INTO ARCHIVO (ID_USUARIO, ID_CARPETA, ID_ICONO, NOMBRE, TIPO, TAMANO, URL)
VALUES (1, 1, 1, 'plan_estudio', 'pdf', 500, 'docs/plan.pdf');

INSERT INTO ARCHIVO (ID_USUARIO, ID_CARPETA, ID_ICONO, NOMBRE, TIPO, TAMANO, URL)
VALUES (1, 2, 2, 'tarea1', 'docx', 300, 'docs/tarea1.docx');

INSERT INTO ARCHIVO (ID_USUARIO, ID_CARPETA, ID_ICONO, NOMBRE, TIPO, TAMANO, URL)
VALUES (2, 3, 3, 'foto_playa', 'jpg', 1500, 'imgs/playa.jpg');

INSERT INTO VERSION (ID_USUARIO, ID_ARCHIVO, NUMERO_VERSION, URL) 
VALUES (1, 1, 'v1', 'docs/plan_v1.pdf');

INSERT INTO VERSION (ID_USUARIO, ID_ARCHIVO, NUMERO_VERSION, URL) 
VALUES (1, 2, 'v2', 'docs/tarea1_v2.docx');

INSERT INTO COMENTARIOS (ID_USUARIO, ID_ARCHIVO, TEXTO)
VALUES (1, 1, 'Revisar la introducción');

INSERT INTO COMENTARIOS (ID_USUARIO, ID_ARCHIVO, TEXTO)
VALUES (2, 1, 'Todo bien');

INSERT INTO PAPELERA (ID_USUARIO, ID_ARCHIVO, TAMANO)
VALUES (1, 2, 300);

INSERT INTO PERMISOS (NOMBRE, DESCRIPCION) VALUES ('Lectura', 'Puede ver el archivo');
INSERT INTO PERMISOS (NOMBRE, DESCRIPCION) VALUES ('Edicion', 'Puede modificar el archivo');
INSERT INTO PERMISOS (NOMBRE, DESCRIPCION) VALUES ('Compartir', 'Puede compartir el archivo');

INSERT INTO ARCHIVO_PERMISO (ID_ARCHIVO, ID_PERMISO) VALUES (1, 1);
INSERT INTO ARCHIVO_PERMISO (ID_ARCHIVO, ID_PERMISO) VALUES (1, 2);

INSERT INTO CARPETA_PERMISO (ID_CARPETA, ID_PERMISO) VALUES (1, 1);
INSERT INTO CARPETA_PERMISO (ID_CARPETA, ID_PERMISO) VALUES (1, 3);

INSERT INTO FAVORITOS (ID_USUARIO, ID_ARCHIVO) VALUES (1, 1);

INSERT INTO SPAM (ID_USUARIO, ID_ARCHIVO) VALUES (2, 3);

INSERT INTO COMPARTIDOS (ID_USUARIO, ID_ARCHIVO, ID_PERMISO) VALUES (2, 1, 1);
INSERT INTO COMPARTIDOS (ID_USUARIO, ID_CARPETA, ID_PERMISO) VALUES (3, 3, 2);

INSERT INTO DESCARGAS (ID_USUARIO, ID_ARCHIVO, DESTINO_DESCARGA, FECHA_DESCARGA, FECHA_ACTUALIZACION)
VALUES (1, 1, 'C:/Downloads', SYSDATE, SYSDATE);

INSERT INTO DESCARGAS (ID_USUARIO, ID_CARPETA, DESTINO_DESCARGA, FECHA_DESCARGA, FECHA_ACTUALIZACION)
VALUES (2, 3, 'C:/Downloads', SYSDATE, SYSDATE);

COMMIT;

