CREATE TABLE PAIS (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE NVARCHAR2(100) NOT NULL
);



CREATE TABLE USUARIO (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE NVARCHAR2(100) NOT NULL,
APELLIDO NVARCHAR2(100) NOT NULL,
CORREO NVARCHAR2(100) NOT NULL UNIQUE,
FOTO NVARCHAR2(100),
ID_PAIS NUMBER,
ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
CONSTRAINT FK_USUARIO_PAIS FOREIGN KEY (ID_PAIS)
REFERENCES PAIS(ID)
);


CREATE TABLE MEMBRESIA (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE NVARCHAR2(100) NOT NULL,
PRECIO NUMBER(10,2) NOT NULL
);




CREATE TABLE UNIDAD (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
CAPACIDAD_TOTAL NUMBER(10,2) NOT NULL,
CAPACIDAD_ACTUAL NUMBER(10,2) NOT NULL,
FECHA_COMPRA DATE,
FECHA_EXPIRACION DATE,
ID_USUARIO NUMBER,
ID_MEMBRESIA NUMBER,
CONSTRAINT FK_UNIDAD_USUARIO FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(ID),
CONSTRAINT FK_UNIDAD_MEMBRESIA FOREIGN KEY (ID_MEMBRESIA)
REFERENCES MEMBRESIA(ID)
);


CREATE TABLE CARPETA (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ID_USUARIO NUMBER NOT NULL,
ID_CARPETA_PADRE NUMBER,
NOMBRE NVARCHAR2(100) NOT NULL,
TAMANO NUMBER(10,2) NOT NULL,
VISIBILIDAD NUMBER(1) DEFAULT 1,
FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
FECHA_MODIFICACION DATE,

CONSTRAINT FK_CARPETA_USUARIO FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(ID),
CONSTRAINT FK_CARPETA_PADRE FOREIGN KEY (ID_CARPETA_PADRE)
REFERENCES CARPETA(ID)
);


CREATE TABLE ICONOS (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE NVARCHAR2(100),
URL NVARCHAR2(150)
);


CREATE TABLE ARCHIVO (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ID_USUARIO NUMBER NOT NULL,
ID_CARPETA NUMBER,
ID_ICONO NUMBER NOT NULL,
NOMBRE NVARCHAR2(100) NOT NULL,
TIPO NVARCHAR2(100) NOT NULL,
TAMANO NUMBER(10,2) NOT NULL,
URL NVARCHAR2(100) NOT NULL UNIQUE,
VISIBILIDAD NUMBER(1) DEFAULT 1,
FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
FECHA_MODIFICACION DATE,
CONSTRAINT FK_ARCHIVO_USUARIO FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(ID),
CONSTRAINT FK_ARCHIVO_CARPETA FOREIGN KEY (ID_CARPETA)
REFERENCES CARPETA(ID),
CONSTRAINT FK_ICONO_CARPETA FOREIGN KEY (ID_ICONO)
REFERENCES ICONOS(ID)
);


CREATE TABLE PAPELERA (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ID_USUARIO NUMBER NOT NULL,
ID_CARPETA NUMBER,
ID_ARCHIVO NUMBER,
TAMANO NUMBER(10,2) NOT NULL,
FECHA_ENTRADA DATE NOT NULL,
FECHA_ELIMINACION DATE NOT NULL,
CONSTRAINT FK_PAPELERA_USUARIO FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(ID),
CONSTRAINT FK_PAPELERA_CARPETA FOREIGN KEY (ID_CARPETA)
REFERENCES CARPETA(ID),
CONSTRAINT FK_PAPELERA_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
REFERENCES ARCHIVO(ID),
CONSTRAINT CHK_PAPELERA_ARCHIVO_CARPETA CHECK (
(ID_ARCHIVO IS NOT NULL AND ID_CARPETA IS NULL) OR
(ID_ARCHIVO IS NULL AND ID_CARPETA IS NOT NULL)
)
);


CREATE TABLE VERSION (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ID_USUARIO NUMBER NOT NULL,
ID_ARCHIVO NUMBER NOT NULL,
NUMERO_VERSION VARCHAR2(100),
URL NVARCHAR2(100) NOT NULL,
FECHA DATE NOT NULL,
CONSTRAINT FK_VERSION_USUARIO FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(ID),
CONSTRAINT FK_VERSION_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
REFERENCES ARCHIVO(ID)
);


CREATE TABLE COMENTARIOS (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ID_USUARIO NUMBER NOT NULL,
ID_ARCHIVO NUMBER NOT NULL,
TEXTO NVARCHAR2(100) NOT NULL,
FECHA DATE NOT NULL,
CONSTRAINT FK_COMENTARIO_USUARIO FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(ID),
CONSTRAINT FK_COMENTARIO_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
REFERENCES ARCHIVO(ID)
);


CREATE TABLE SPAM (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ID_USUARIO NUMBER NOT NULL,
ID_ARCHIVO NUMBER,
ID_CARPETA NUMBER,
FECHA DATE NOT NULL,
CONSTRAINT FK_SPAM_USUARIO FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(ID),
CONSTRAINT FK_SPAM_CARPETA FOREIGN KEY (ID_CARPETA)
REFERENCES CARPETA(ID),
CONSTRAINT FK_SPAM_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
REFERENCES ARCHIVO(ID),
CONSTRAINT CHK_SPAM_ARCHIVO_CARPETA CHECK (
(ID_ARCHIVO IS NOT NULL AND ID_CARPETA IS NULL) OR
(ID_ARCHIVO IS NULL AND ID_CARPETA IS NOT NULL)
)
);


CREATE TABLE FAVORITOS (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ID_USUARIO NUMBER NOT NULL,
ID_CARPETA NUMBER,
ID_ARCHIVO NUMBER,
FECHA_AGREGADO DATE NOT NULL,
CONSTRAINT FK_FAVORITOS_USUARIO FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(ID),
CONSTRAINT FK_FAVORITOS_CARPETA FOREIGN KEY (ID_CARPETA)
REFERENCES CARPETA(ID),
CONSTRAINT FK_FAVORITOS_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
REFERENCES ARCHIVO(ID),
CONSTRAINT CHK_FAVORITOS_ARCHIVO_CARPETA CHECK (
(ID_ARCHIVO IS NOT NULL AND ID_CARPETA IS NULL) OR
(ID_ARCHIVO IS NULL AND ID_CARPETA IS NOT NULL)
)
);


CREATE TABLE DESCARGAS (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ID_USUARIO NUMBER NOT NULL,
ID_ARCHIVO NUMBER,
ID_CARPETA NUMBER,
DESTINO_DESCARGA NVARCHAR2(100) NOT NULL,
FECHA_DESCARGA DATE NOT NULL,
FECHA_ACTUALIZACION DATE NOT NULL,
CONSTRAINT FK_DESCARGAS_USUARIO FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(ID),
CONSTRAINT FK_DESCARGAS_CARPETA FOREIGN KEY (ID_CARPETA)
REFERENCES CARPETA(ID),
CONSTRAINT FK_DESCARGAS_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
REFERENCES ARCHIVO(ID),
CONSTRAINT CHK_DESCARGAS_ARCHIVO_CARPETA CHECK (
(ID_ARCHIVO IS NOT NULL AND ID_CARPETA IS NULL) OR
(ID_ARCHIVO IS NULL AND ID_CARPETA IS NOT NULL)
)
);



CREATE TABLE PERMISOS (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE NVARCHAR2(100) NOT NULL,
DESCRIPCION NVARCHAR2(100) NOT NULL
);


CREATE TABLE ARCHIVO_PERMISO (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ID_ARCHIVO NUMBER NOT NULL,
ID_PERMISO NUMBER NOT NULL,
CONSTRAINT FK_ARCHIVOPERMISO_PERMISO FOREIGN KEY (ID_PERMISO)
REFERENCES PERMISOS(ID),
CONSTRAINT FK_ARCHIVOPERMISO_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
REFERENCES ARCHIVO(ID)
);



CREATE TABLE CARPETA_PERMISO (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ID_CARPETA NUMBER NOT NULL,
ID_PERMISO NUMBER NOT NULL,
CONSTRAINT FK_CARPETAPERMISO_PERMISO FOREIGN KEY (ID_PERMISO)
REFERENCES PERMISOS(ID),
CONSTRAINT FK_CARPETAPERMISO_CARPETA FOREIGN KEY (ID_CARPETA)
REFERENCES CARPETA(ID)
);



CREATE TABLE COMPARTIDOS (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ID_USUARIO NUMBER NOT NULL,
ID_ARCHIVO NUMBER,
ID_CARPETA NUMBER,
ID_PERMISO NUMBER NOT NULL,
CONSTRAINT FK_COMPARTIDO_USUARIO FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO(ID),
CONSTRAINT FK_COMPARTIDO_CARPETA FOREIGN KEY (ID_CARPETA)
REFERENCES CARPETA(ID),
CONSTRAINT FK_COMPARTIDO_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
REFERENCES ARCHIVO(ID),
CONSTRAINT FK_COMPARTIDO_PERMISO FOREIGN KEY (ID_PERMISO)
REFERENCES PERMISOS(ID),
CONSTRAINT CHK_COMPARTIDOS_ARCHIVO_CARPETA CHECK (
(ID_ARCHIVO IS NOT NULL AND ID_CARPETA IS NULL) OR
(ID_ARCHIVO IS NULL AND ID_CARPETA IS NOT NULL)
)
);

CREATE OR REPLACE TRIGGER TR_CARPETA_FECHA_MODIFICACION
BEFORE UPDATE ON CARPETA
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/



CREATE OR REPLACE TRIGGER TR_ARCHIVO_FECHA_MODIFICACION
BEFORE UPDATE ON ARCHIVO
FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/


CREATE OR REPLACE TRIGGER TRG_SET_TAMANO_CARPETA
BEFORE INSERT ON CARPETA
FOR EACH ROW
BEGIN
    SELECT NVL(SUM(A.TAMANO), 0)
    INTO :NEW.TAMANO
    FROM ARCHIVO A
    WHERE A.ID_CARPETA = :NEW.ID;
END;
/

DROP TRIGGER TR_CARPETA_FECHA_MODIFICACION;
