CREATE SCHEMA GD;
GO

CREATE TABLE GD.PAIS(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE GD.USUARIO(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    APELLIDO NVARCHAR(100) NOT NULL,
    CORREO NVARCHAR(100) NOT NULL UNIQUE,
    FOTO NVARCHAR(100),
    ID_PAIS INT,
    CONSTRAINT FK_USUARIO_PAIS FOREIGN KEY (ID_PAIS)
        REFERENCES GD.PAIS(ID)
);
GO

CREATE TABLE GD.MEMBRESIA(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL
);
GO

CREATE TABLE GD.UNIDAD(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    CAPACIDAD_TOTAL DECIMAL(10,2) NOT NULL,
    CAPACIDAD_ACTUAL DECIMAL(10,2) NOT NULL,
    FECHA_COMPRA DATE,
    FECHA_EXPIRACION DATE,
    ID_USUARIO INT,
    ID_MEMBRESIA INT,
    CONSTRAINT FK_UNIDAD_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_UNIDAD_MEMBRESIA FOREIGN KEY (ID_MEMBRESIA)
        REFERENCES GD.MEMBRESIA(ID)
);
GO

CREATE TABLE GD.CARPETA(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_CARPETA_PADRE INT NULL,  
    NOMBRE NVARCHAR(100) NOT NULL,  
    TAMAÑO DECIMAL(10,2) NOT NULL,
    VISIBILIDAD CHAR(1),
    FECHA_CREACION DATE NOT NULL,
    FECHA_MODIFICACION DATE NOT NULL,
    CONSTRAINT FK_CARPETA_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_CARPETA_PADRE FOREIGN KEY (ID_CARPETA_PADRE)
        REFERENCES GD.CARPETA(ID)
);
GO

CREATE TABLE GD.ICONOS(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100),
    URL NVARCHAR(150)
);
GO

CREATE TABLE GD.ARCHIVO(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_CARPETA INT,
    ID_ICONO INT NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    TIPO NVARCHAR(100) NOT NULL,
    TAMAÑO DECIMAL(10,2) NOT NULL,
    URL NVARCHAR(100) NOT NULL UNIQUE,
    VISIBILIDAD CHAR(1),
    FECHA_CREACION DATE NOT NULL,
    FECHA_MODIFICACION DATE NOT NULL,
    CONSTRAINT FK_ARCHIVO_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_ARCHIVO_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_ICONO_CARPETA FOREIGN KEY (ID_ICONO)
        REFERENCES GD.ICONOS(ID)
);
GO

CREATE TABLE GD.PAPELERA(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_CARPETA INT,
    ID_ARCHIVO INT,
    TAMAÑO DECIMAL(10,2) NOT NULL,
    FECHA_ENTRADA DATE NOT NULL,
    FECHA_ELIMINACION DATE NOT NULL,
    CONSTRAINT FK_PAPELERA_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_PAPELERA_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_PAPELERA_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.VERSION(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_ARCHIVO INT NOT NULL,
    NUMERO_VERSION VARCHAR(100),
    URL NVARCHAR(100) NOT NULL,
    FECHA DATE NOT NULL,
    CONSTRAINT FK_VERSION_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_VERSION_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.COMENTARIOS(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_ARCHIVO INT NOT NULL,
    TEXTO NVARCHAR(100) NOT NULL,
    FECHA DATE NOT NULL,
    CONSTRAINT FK_COMENTARIO_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_COMENTARIO_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.SPAM(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_ARCHIVO INT,
    ID_CARPETA INT,
    FECHA DATE NOT NULL,
    CONSTRAINT FK_SPAM_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_SPAM_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_SPAM_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.FAVORITOS(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_CARPETA INT NOT NULL,
    ID_ARCHIVO INT NOT NULL,
    FECHA_AGREGADO DATE NOT NULL,
    CONSTRAINT FK_FAVORITOS_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_FAVORITOS_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_FAVORITOS_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.DESCARGAS(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_ARCHIVO INT,
    ID_CARPETA INT,
    DESTINO_DESCARGA NVARCHAR(100) NOT NULL,
    FECHA_DESCARGA DATE NOT NULL,
    FECHA_ACTUALIZACION DATE NOT NULL,
    CONSTRAINT FK_DESCARGAS_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_DESCARGAS_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_DESCARGAS_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.PERMISOS(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    DESCRIPCION NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE GD.ARCHIVO_PERMISO(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_ARCHIVO INT NOT NULL,
    ID_PERMISO INT NOT NULL,
    CONSTRAINT FK_ARCHIVOPERMISO_PERMISO FOREIGN KEY (ID_PERMISO)
        REFERENCES GD.PERMISOS(ID),
    CONSTRAINT FK_ARCHIVOPERMISO_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.CARPETA_PERMISO(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_CARPETA INT NOT NULL,
    ID_PERMISO INT NOT NULL,
    CONSTRAINT FK_CARPETAPERMISO_PERMISO FOREIGN KEY (ID_PERMISO)
        REFERENCES GD.PERMISOS(ID),
    CONSTRAINT FK_CARPETAPERMISO_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID)
);
GO

CREATE TABLE GD.COMPARTIDOS(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_ARCHIVO INT,
    ID_CARPETA INT,
    ID_PERMISO INT NOT NULL,
    CONSTRAINT FK_COMPARTIDO_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_COMPARTIDO_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_COMPARTIDO_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID),
    CONSTRAINT FK_COMPARTIDO_PERMISO FOREIGN KEY (ID_PERMISO)
        REFERENCES GD.PERMISOS(ID)
);
GO


INSERT INTO GD.PAIS (NOMBRE)
VALUES ('Honduras'),
       ('España'),
       ('Estados Unidos');

INSERT INTO GD.USUARIO (NOMBRE, APELLIDO, CORREO, FOTO, ID_PAIS)
VALUES ('Kevin', 'Flores', 'kevin@gmail.com', 'url_foto.jpg', 1),
       ('Maria', 'Lopez', 'maria@gmail.com', 'foto2.png', 2);

INSERT INTO GD.MEMBRESIA (NOMBRE, PRECIO)
VALUES ('Gratis', 0.00),
       ('Premium', 9.99);

INSERT INTO GD.UNIDAD (CAPACIDAD_TOTAL, CAPACIDAD_ACTUAL, FECHA_COMPRA, FECHA_EXPIRACION, ID_USUARIO, ID_MEMBRESIA)
VALUES (50.00, 10.00, '2025-01-01', '2026-01-01', 1, 1),
       (200.00, 25.00, '2025-02-01', '2026-02-01', 2, 2);

INSERT INTO GD.CARPETA (ID_USUARIO, ID_CARPETA_PADRE, NOMBRE, TAMAÑO, VISIBILIDAD, FECHA_CREACION, FECHA_MODIFICACION)
VALUES (1, NULL, 'Documentos', 0, 'P', GETDATE(), GETDATE());

INSERT INTO GD.CARPETA (ID_USUARIO, ID_CARPETA_PADRE, NOMBRE, TAMAÑO, VISIBILIDAD, FECHA_CREACION, FECHA_MODIFICACION)
VALUES (1, 1, 'Fotos', 0, 'P', GETDATE(), GETDATE());

INSERT INTO GD.ICONOS (NOMBRE, URL)
VALUES ('Imagen', 'icon_image.png'),
       ('PDF', 'icon_pdf.png'),
       ('Carpeta', 'icon_folder.png');

INSERT INTO GD.ARCHIVO (ID_USUARIO, ID_CARPETA, ID_ICONO, NOMBRE, TIPO, TAMAÑO, URL, VISIBILIDAD, FECHA_CREACION, FECHA_MODIFICACION)
VALUES (1, 1, 1, 'foto1.jpg', 'imagen', 2.5, 'files/foto1.jpg', 'P', GETDATE(), GETDATE()),
       (1, 2, 2, 'documento.pdf', 'pdf', 1.2, 'files/documento.pdf', 'P', GETDATE(), GETDATE());

INSERT INTO GD.PAPELERA (ID_USUARIO, ID_CARPETA, ID_ARCHIVO, TAMAÑO, FECHA_ENTRADA, FECHA_ELIMINACION)
VALUES (1, 1, 1, 2.5, GETDATE(), DATEADD(day, 30, GETDATE()));

INSERT INTO GD.VERSION (ID_USUARIO, ID_ARCHIVO, NUMERO_VERSION, URL, FECHA)
VALUES (1, 1, 'v1.0', 'files/foto1_v1.jpg', GETDATE());

INSERT INTO GD.COMENTARIOS (ID_USUARIO, ID_ARCHIVO, TEXTO, FECHA)
VALUES (2, 1, 'Muy buena foto', GETDATE());

INSERT INTO GD.SPAM (ID_USUARIO, ID_ARCHIVO, ID_CARPETA, FECHA)
VALUES (2, 1, NULL, GETDATE());

INSERT INTO GD.FAVORITOS (ID_USUARIO, ID_CARPETA, ID_ARCHIVO, FECHA_AGREGADO)
VALUES (1, 1, 1, GETDATE());

INSERT INTO GD.DESCARGAS (ID_USUARIO, ID_ARCHIVO, ID_CARPETA, DESTINO_DESCARGA, FECHA_DESCARGA, FECHA_ACTUALIZACION)
VALUES (1, 1, 1, 'C:/Descargas', GETDATE(), GETDATE());

INSERT INTO GD.PERMISOS (NOMBRE, DESCRIPCION)
VALUES ('Lectura', 'Puede ver el archivo'),
       ('Edicion', 'Puede editar el archivo'),
       ('Compartir', 'Puede compartir el archivo');

INSERT INTO GD.ARCHIVO_PERMISO (ID_ARCHIVO, ID_PERMISO)
VALUES (1, 1), (1, 2);

INSERT INTO GD.CARPETA_PERMISO (ID_CARPETA, ID_PERMISO)
VALUES (1, 1), (1, 3);

INSERT INTO GD.COMPARTIDOS (ID_USUARIO, ID_ARCHIVO, ID_CARPETA, ID_PERMISO)
VALUES (2, 1, NULL, 1),
       (2, NULL, 1, 3);


CREATE SCHEMA GD;
GO

CREATE TABLE GD.PAIS(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE GD.USUARIO(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    APELLIDO NVARCHAR(100) NOT NULL,
    CORREO NVARCHAR(100) NOT NULL UNIQUE,
    FOTO NVARCHAR(100),
    ID_PAIS INT,
    CONSTRAINT FK_USUARIO_PAIS FOREIGN KEY (ID_PAIS)
        REFERENCES GD.PAIS(ID)
);
GO

CREATE TABLE GD.MEMBRESIA(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL
);
GO

CREATE TABLE GD.UNIDAD(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    CAPACIDAD_TOTAL DECIMAL(10,2) NOT NULL,
    CAPACIDAD_ACTUAL DECIMAL(10,2) NOT NULL,
    FECHA_COMPRA DATE,
    FECHA_EXPIRACION DATE,
    ID_USUARIO INT,
    ID_MEMBRESIA INT,
    CONSTRAINT FK_UNIDAD_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_UNIDAD_MEMBRESIA FOREIGN KEY (ID_MEMBRESIA)
        REFERENCES GD.MEMBRESIA(ID)
);
GO

CREATE TABLE GD.CARPETA(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_CARPETA_PADRE INT NULL,  
    NOMBRE NVARCHAR(100) NOT NULL,  
    TAMAÑO DECIMAL(10,2) NOT NULL,
    VISIBILIDAD CHAR(1),
    FECHA_CREACION DATE NOT NULL,
    FECHA_MODIFICACION DATE NOT NULL,
    CONSTRAINT FK_CARPETA_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_CARPETA_PADRE FOREIGN KEY (ID_CARPETA_PADRE)
        REFERENCES GD.CARPETA(ID)
);
GO

CREATE TABLE GD.ICONOS(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100),
    URL NVARCHAR(150)
);
GO

CREATE TABLE GD.ARCHIVO(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_CARPETA INT,
    ID_ICONO INT NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    TIPO NVARCHAR(100) NOT NULL,
    TAMAÑO DECIMAL(10,2) NOT NULL,
    URL NVARCHAR(100) NOT NULL UNIQUE,
    VISIBILIDAD CHAR(1),
    FECHA_CREACION DATE NOT NULL,
    FECHA_MODIFICACION DATE NOT NULL,
    CONSTRAINT FK_ARCHIVO_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_ARCHIVO_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_ICONO_CARPETA FOREIGN KEY (ID_ICONO)
        REFERENCES GD.ICONOS(ID)
);
GO

CREATE TABLE GD.PAPELERA(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_CARPETA INT,
    ID_ARCHIVO INT,
    TAMAÑO DECIMAL(10,2) NOT NULL,
    FECHA_ENTRADA DATE NOT NULL,
    FECHA_ELIMINACION DATE NOT NULL,
    CONSTRAINT FK_PAPELERA_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_PAPELERA_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_PAPELERA_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.VERSION(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_ARCHIVO INT NOT NULL,
    NUMERO_VERSION VARCHAR(100),
    URL NVARCHAR(100) NOT NULL,
    FECHA DATE NOT NULL,
    CONSTRAINT FK_VERSION_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_VERSION_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.COMENTARIOS(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_ARCHIVO INT NOT NULL,
    TEXTO NVARCHAR(100) NOT NULL,
    FECHA DATE NOT NULL,
    CONSTRAINT FK_COMENTARIO_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_COMENTARIO_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.SPAM(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_ARCHIVO INT,
    ID_CARPETA INT,
    FECHA DATE NOT NULL,
    CONSTRAINT FK_SPAM_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_SPAM_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_SPAM_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.FAVORITOS(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_CARPETA INT NOT NULL,
    ID_ARCHIVO INT NOT NULL,
    FECHA_AGREGADO DATE NOT NULL,
    CONSTRAINT FK_FAVORITOS_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_FAVORITOS_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_FAVORITOS_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.DESCARGAS(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_ARCHIVO INT,
    ID_CARPETA INT,
    DESTINO_DESCARGA NVARCHAR(100) NOT NULL,
    FECHA_DESCARGA DATE NOT NULL,
    FECHA_ACTUALIZACION DATE NOT NULL,
    CONSTRAINT FK_DESCARGAS_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_DESCARGAS_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_DESCARGAS_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.PERMISOS(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    DESCRIPCION NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE GD.ARCHIVO_PERMISO(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_ARCHIVO INT NOT NULL,
    ID_PERMISO INT NOT NULL,
    CONSTRAINT FK_ARCHIVOPERMISO_PERMISO FOREIGN KEY (ID_PERMISO)
        REFERENCES GD.PERMISOS(ID),
    CONSTRAINT FK_ARCHIVOPERMISO_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID)
);
GO

CREATE TABLE GD.CARPETA_PERMISO(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_CARPETA INT NOT NULL,
    ID_PERMISO INT NOT NULL,
    CONSTRAINT FK_CARPETAPERMISO_PERMISO FOREIGN KEY (ID_PERMISO)
        REFERENCES GD.PERMISOS(ID),
    CONSTRAINT FK_CARPETAPERMISO_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID)
);
GO

CREATE TABLE GD.COMPARTIDOS(
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_ARCHIVO INT,
    ID_CARPETA INT,
    ID_PERMISO INT NOT NULL,
    CONSTRAINT FK_COMPARTIDO_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES GD.USUARIO(ID),
    CONSTRAINT FK_COMPARTIDO_CARPETA FOREIGN KEY (ID_CARPETA)
        REFERENCES GD.CARPETA(ID),
    CONSTRAINT FK_COMPARTIDO_ARCHIVO FOREIGN KEY (ID_ARCHIVO)
        REFERENCES GD.ARCHIVO(ID),
    CONSTRAINT FK_COMPARTIDO_PERMISO FOREIGN KEY (ID_PERMISO)
        REFERENCES GD.PERMISOS(ID)
);
GO


INSERT INTO GD.PAIS (NOMBRE)
VALUES ('Honduras'),
       ('España'),
       ('Estados Unidos');

INSERT INTO GD.USUARIO (NOMBRE, APELLIDO, CORREO, FOTO, ID_PAIS)
VALUES ('Kevin', 'Flores', 'kevin@gmail.com', 'url_foto.jpg', 1),
       ('Maria', 'Lopez', 'maria@gmail.com', 'foto2.png', 2);

INSERT INTO GD.MEMBRESIA (NOMBRE, PRECIO)
VALUES ('Gratis', 0.00),
       ('Premium', 9.99);

INSERT INTO GD.UNIDAD (CAPACIDAD_TOTAL, CAPACIDAD_ACTUAL, FECHA_COMPRA, FECHA_EXPIRACION, ID_USUARIO, ID_MEMBRESIA)
VALUES (50.00, 10.00, '2025-01-01', '2026-01-01', 1, 1),
       (200.00, 25.00, '2025-02-01', '2026-02-01', 2, 2);

INSERT INTO GD.CARPETA (ID_USUARIO, ID_CARPETA_PADRE, NOMBRE, TAMAÑO, VISIBILIDAD, FECHA_CREACION, FECHA_MODIFICACION)
VALUES (1, NULL, 'Documentos', 0, 'P', GETDATE(), GETDATE());

INSERT INTO GD.CARPETA (ID_USUARIO, ID_CARPETA_PADRE, NOMBRE, TAMAÑO, VISIBILIDAD, FECHA_CREACION, FECHA_MODIFICACION)
VALUES (1, 1, 'Fotos', 0, 'P', GETDATE(), GETDATE());

INSERT INTO GD.ICONOS (NOMBRE, URL)
VALUES ('Imagen', 'icon_image.png'),
       ('PDF', 'icon_pdf.png'),
       ('Carpeta', 'icon_folder.png');

INSERT INTO GD.ARCHIVO (ID_USUARIO, ID_CARPETA, ID_ICONO, NOMBRE, TIPO, TAMAÑO, URL, VISIBILIDAD, FECHA_CREACION, FECHA_MODIFICACION)
VALUES (1, 1, 1, 'foto1.jpg', 'imagen', 2.5, 'files/foto1.jpg', 'P', GETDATE(), GETDATE()),
       (1, 2, 2, 'documento.pdf', 'pdf', 1.2, 'files/documento.pdf', 'P', GETDATE(), GETDATE());

INSERT INTO GD.PAPELERA (ID_USUARIO, ID_CARPETA, ID_ARCHIVO, TAMAÑO, FECHA_ENTRADA, FECHA_ELIMINACION)
VALUES (1, 1, 1, 2.5, GETDATE(), DATEADD(day, 30, GETDATE()));

INSERT INTO GD.VERSION (ID_USUARIO, ID_ARCHIVO, NUMERO_VERSION, URL, FECHA)
VALUES (1, 1, 'v1.0', 'files/foto1_v1.jpg', GETDATE());

INSERT INTO GD.COMENTARIOS (ID_USUARIO, ID_ARCHIVO, TEXTO, FECHA)
VALUES (2, 1, 'Muy buena foto', GETDATE());

INSERT INTO GD.SPAM (ID_USUARIO, ID_ARCHIVO, ID_CARPETA, FECHA)
VALUES (2, 1, NULL, GETDATE());

INSERT INTO GD.FAVORITOS (ID_USUARIO, ID_CARPETA, ID_ARCHIVO, FECHA_AGREGADO)
VALUES (1, 1, 1, GETDATE());

INSERT INTO GD.DESCARGAS (ID_USUARIO, ID_ARCHIVO, ID_CARPETA, DESTINO_DESCARGA, FECHA_DESCARGA, FECHA_ACTUALIZACION)
VALUES (1, 1, 1, 'C:/Descargas', GETDATE(), GETDATE());

INSERT INTO GD.PERMISOS (NOMBRE, DESCRIPCION)
VALUES ('Lectura', 'Puede ver el archivo'),
       ('Edicion', 'Puede editar el archivo'),
       ('Compartir', 'Puede compartir el archivo');

INSERT INTO GD.ARCHIVO_PERMISO (ID_ARCHIVO, ID_PERMISO)
VALUES (1, 1), (1, 2);

INSERT INTO GD.CARPETA_PERMISO (ID_CARPETA, ID_PERMISO)
VALUES (1, 1), (1, 3);

INSERT INTO GD.COMPARTIDOS (ID_USUARIO, ID_ARCHIVO, ID_CARPETA, ID_PERMISO)
VALUES (2, 1, NULL, 1),
       (2, NULL, 1, 3);

ALTER TABLE GD.USUARIO
ADD ACTIVO CHAR(1) NOT NULL
    CONSTRAINT DF_USUARIO_ACTIVO DEFAULT 'Y';
GO
